---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wenzhihuai.
--- DateTime: 2018/6/6 18:03
---

function writefile(content)
    local file = io.open("D:\\mavenproject\\micro-service\\conf\\lua\\hello.log", "a")
    if file then
        if file:write(content) == nil then
            return false
        end
        io.close(file)
        return true
    else
        return false
    end
end


writefile("aaaa")